import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import settingsRouter from "./settings.js";
import clientsRouter from "./clients.js";
import brandDnaRouter from "./brand_dna.js";
import brandAssetsRouter from "./brand_assets.js";
import storylinesRouter from "./storylines.js";
import postsRouter from "./posts.js";
import campaignsRouter from "./campaigns.js";
import imagesRouter from "./images.js";
import memoryRouter from "./memory.js";
import dashboardRouter from "./dashboard.js";
import aiRouter from "./ai.js";
import aiContentRouter from "./ai_content.js";
import uploadRouter from "./upload.js";
import socialAccountsRouter from "./social_accounts.js";
import oauthRouter from "./oauth.js";
import publishRouter from "./publish.js";
import postingRulesRouter from "./posting_rules.js";
import aiBrainRouter from "./ai_brain.js";
import campaignGenerateRouter from "./campaign_generate.js";
import blogStudioRouter from "./blog_studio.js";
import blogPublishingRouter from "./blog_publishing.js";
import imageStudioRouter from "./image_studio.js";
import videoStudioRouter from "./video_studio.js";
import creativeRouter from "./creative.js";
import skillsRouter from "./skills.js";
import aiProviderHealthRouter from "./ai_provider_health.js";
import occasionsRouter from "./occasions.js";
import analyticsRouter from "./analytics.js";
import socialIntelligenceRouter from "./social_intelligence.js";
import reportsRouter from "./reports.js";
import storageArchiveRouter from "./storage_archive.js";
import teamRouter from "./team.js";
import notificationsRouter from "./notifications.js";
import trendsRouter from "./trends.js";
import growthAdvisorRouter from "./growth_advisor.js";
import aiVisibilityRouter from "./ai-visibility.js";
import formatMatrixRouter from "./format_matrix.js";
import omnichannelRouter from "./omnichannel.js";
import gbpRouter from "./gbp.js";
import videoRenderRouter, { renderWorkerWebhookRouter } from "./video_render.js";
import driveArchiveRouter from "./drive_archive.js";
import { requireAuth, requireClientAccess } from "../middleware/auth.js";

const router: IRouter = Router();

router.use(authRouter);
router.use(oauthRouter);
router.use(healthRouter);
router.use(renderWorkerWebhookRouter); // public — auth via shared secret header

router.use(requireAuth);
router.use(teamRouter);
router.use("/clients/:clientId", requireClientAccess());

router.use(settingsRouter);
router.use(aiProviderHealthRouter);
router.use(clientsRouter);
router.use(brandDnaRouter);
router.use(brandAssetsRouter);
router.use(storylinesRouter);
router.use(postsRouter);
router.use(publishRouter);
router.use(campaignsRouter);
router.use(imagesRouter);
router.use(memoryRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(aiContentRouter);
router.use(uploadRouter);
router.use(socialAccountsRouter);
router.use(postingRulesRouter);
router.use(aiBrainRouter);
router.use(campaignGenerateRouter);
router.use(blogStudioRouter);
router.use(blogPublishingRouter);
router.use(imageStudioRouter);
router.use(videoStudioRouter);
router.use(creativeRouter);
router.use(skillsRouter);
router.use(occasionsRouter);
router.use(analyticsRouter);
router.use(socialIntelligenceRouter);
router.use(reportsRouter);
router.use(storageArchiveRouter);
router.use(notificationsRouter);
router.use(trendsRouter);
router.use(growthAdvisorRouter);
router.use(aiVisibilityRouter);
router.use(formatMatrixRouter);
router.use(omnichannelRouter);
router.use(gbpRouter);
router.use(videoRenderRouter);
router.use(driveArchiveRouter);

export default router;
